function cfg = kiaSort_main_configs()

cfg = struct(...
    'dataType',                'int16', ...          % data type: 'int16', 'float32', etc.
    'numChannels',              128, ...             % Number of channels
    'samplingFrequency',        3E4, ...             % Sampling frequency (Hz)
    'commonRef',               'median', ...           % Type of common referencing
    'denoising',                true, ...            % remove shared noise if true
    'extremeNoise',             false,...
    'noisePrctile',             60,...               % perctile of channels showing similar noise pattern
    'noiseCorr',                0.4,...              % noise correlation threshold    
    'num_channel_extract',      5, ...               % Number of channels to extract before and after each channel
    'waveform_radius',          150, ...              % radius based on which number of channels for waveform is selected
    'bandpass',                 [500 6000], ...      % Bandpass frequency range (Hz)
    'min_threshold',            5.5, ...               % Minimum threshold (based on RMS after one round of spike exclusion)
    'numSampleChunks',          300, ...              % Number of sample chunks
    'sortingChunkDuration',     120, ...             % Duration (in seconds) for sorting each chunk of signal
    'sort_only',                false,...
    'useGPU',                   true, ...            % Use GPU acceleration if available
    'parallelProcessing',       false, ...           % Enable parallel processing
    'extractWaveform',          false ...            % Flag to extract and save waveforms after sorting
    );

cfg.varName = struct(...
    'dataType',                 'Data Format', ...
    'numChannels',              'Num. Channels', ...
    'samplingFrequency',        'Sampling Freq (Hz)', ...
    'commonRef',                'Common Ref. Type', ...
    'denoising',                'Whitening',...
    'extremeNoise',             'Denoising',...
    'noisePrctile',             'Noisy Ch Percentile',...
    'noiseCorr',                'Noise Corr Thr.',...     
    'num_channel_extract',      'Max Half-channel Count', ...
    'waveform_radius',          'Channel Selection Radius',...
    'bandpass',                 'Bandpass Range (Hz)', ...
    'min_threshold',            'Min Thr.', ...
    'numSampleChunks',          'Num. Sample Chunks', ...
    'sortingChunkDuration',     'Sort Chunk Duration (s)', ...
    'sort_only',                'Sort Only',...
    'useGPU',                   'Use GPU', ...
    'parallelProcessing',       'Parallel Proc', ...
    'extractWaveform',          'Save Sorted Waveforms' ...
    );

end