function cfg = kiaSort_hidden_configs(cfg)

extra_cfg = struct(...
    'numBands',                 4, ...               % Number of frequency bands for multiband extraction
    'borderMargin',             2, ...               % Minimum spike margin from start/end (ms)
    'edgeSampleExclusion',      2, ...               % Exclusion (ms) for edge samples
    'spikeSampleDistance',      1, ...               % Spike sample distance (ms)
    'method',                   "direct", ...        % Sorting method ("direct" or "indirect")
    'residual_template',        true,...             % second round of detection
    'numTemplatesPerCluster',   15,...              % number of template variants per cluster  
    'postHocProcessing',        true,...            % process groups posthoc
    'overlap_thr',              0.2,...             % Maximum allowed template overlap
    'duplicateSearchChannels',  2,...               % Cross-channel duplicate radius when num_channel_extract is 0
    'contaminationThr',         0.5, ...            % Reject sample spike if any side-window peak > this * centre peak
    'bimodalSeparability',      0.75, ...           % Split: Otsu separability of the best cut (0-1)
    'bimodalMinSepDistance',    1.75, ...           % Split: alternative detection, mode distance in pooled sd
    'bimodalCcgIndepMin',       0.5, ...            % Split: min coincidence-over-chance between children (independence)
    'bimodalCcgMinExpected',    20, ...             % Split: independence test abstains below this expected count
    'bimodalAssignMinAgree',    0.75, ...           % Split: min agreement of the waveform assignment with the amplitude cut
    'bimodalMinChildFrac',      0.20, ...           % Split: min child size as a fraction of the parent
    'bimodalMinTimeOverlap',    0.5, ...            % Split: min temporal overlap of the two children
    'bimodalMaxMedianShift',    0.3, ...            % Split: max median-time separation
    'bimodalMaxSplits',         1, ...              % Split: max extra splits per channel
    'bimodalMaxTestPoints',     5000, ...           % Split: subsample cap
    'bimodalNumBins',           64, ...             % Split: histogram bins
    'ampSplitSeparability',     0.75, ...           % Amp split: Otsu separability of the best cut (0-1)
    'ampSplitMinChildFrac',     0.15, ...           % Amp split: min child size as a fraction
    'ampSplitMaxPerChannel',    1, ...              % Amp split: max per channel
    'noiseSinkTemplates',       3, ...              % Sink: template variants
    'noiseSinkMaxTemplatePts',  5000, ...           % Sink: subsample cap for templates
    'corrScaleRefChannels',     9, ...               % Footprint width at/above which merge gates are unscaled
    'noiseSinkSnr',             1.25, ...            % Sink band, in units of the channel threshold
    'ampBandLowFactor',         0.5, ...            % Template amp band: factor on the class 1st percentile
    'ampBandHighFactor',        Inf, ...            % Template amp band: upper cap (Inf = none; it truncated real units)
    'keepAmpSnr',               1.25, ...           % Class is dropped if its template peak is below this x channel threshold
    'postHocRemoval',           true, ...            % Post-hoc: overlap/duplicate removal
    'postHocDriftMerge',        true  ...            % Post-hoc: drift-aware merge pass
    );

% Append any missing fields from extra_cfg to cfg
extra_fields = fieldnames(extra_cfg);
for i = 1:length(extra_fields)
    field = extra_fields{i};
    if ~isfield(cfg, field)
        cfg.(field) = extra_cfg.(field);
    end
end

extra_varName = struct(...
    'numBands',                'Num. Frequency Bands', ...
    'borderMargin',            'Border margin (ms)', ...
    'edgeSampleExclusion',     'Edge Exclusion (ms)', ...
    'spikeSampleDistance',     'Sample spk Dist. (ms)', ...
    'method',                  'Sorting: Method', ...
    'residual_template',       'Second round of sorting',...
    'numTemplatesPerCluster',  'Number of template variants',...
    'postHocProcessing',       'Process clusters posthoc',...
    'overlap_thr',             'Cluster Overlap Thr',...
    'duplicateSearchChannels', 'Duplicate Search Half-window',...
    'contaminationThr',        'Sample Contamination Thr',...
    'bimodalSeparability',     'Split: Separability',...
    'bimodalMinSepDistance',   'Split: Min Mode Distance', ...
    'bimodalCcgIndepMin',      'Split: Min CCG Independence', ...
    'bimodalCcgMinExpected',   'Split: CCG Min Expected', ...
    'bimodalAssignMinAgree',   'Split: Assign Min Agreement', ...
    'bimodalMinChildFrac',     'Split: Min Child Frac',...
    'bimodalMinTimeOverlap',   'Split: Min Time Overlap',...
    'bimodalMaxMedianShift',   'Split: Max Median Shift',...
    'bimodalMaxSplits',        'Split: Max Per Channel',...
    'bimodalMaxTestPoints',    'Split: Test Points',...
    'bimodalNumBins',          'Split: Hist Bins',...
    'ampSplitSeparability',    'Amp Split: Separability',...
    'ampSplitMinChildFrac',    'Amp Split: Min Child Frac',...
    'ampSplitMaxPerChannel',   'Amp Split: Max Per Channel',...
    'noiseSinkTemplates',      'Sink: Template Variants',...
    'noiseSinkMaxTemplatePts', 'Sink: Template Points',...
    'corrScaleRefChannels',    'Merge Scale Ref Width', ...
    'noiseSinkSnr',            'Noise Sink SNR', ...
    'ampBandLowFactor',        'Amp Band: Low Factor',...
    'ampBandHighFactor',       'Amp Band: High Factor',...
    'keepAmpSnr',              'Keep Amp SNR', ...
    'postHocRemoval',          'Posthoc: Removal', ...
    'postHocDriftMerge',       'Posthoc: Drift Merge' ...
);

if ~isfield(cfg, 'varName')
    cfg.varName = struct();
end

% Append varName fields to cfg.varName
extra_var_fields = fieldnames(extra_varName);
for i = 1:length(extra_var_fields)
    key = extra_var_fields{i};
    if ~isfield(cfg.varName, key)
        cfg.varName.(key) = extra_varName.(key);
    end
end

allFields = fieldnames(cfg);
fieldsWithoutVarName = setdiff(allFields, {'varName'}, 'stable');
cfg = orderfields(cfg, [fieldsWithoutVarName; {'varName'}]);

end